apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-config
  labels:
    app: webhook-server
webhooks:
  - name: mutating-webhook.drlatt.com
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: webhook-server
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["", "apps"]
        apiVersions: ["v1"]
        resources: ["pods", "deployments"]
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  labels:
    app: webhook-server
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: webhook-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      name: webhook-server
      labels:
        app: webhook-server
    spec:
      containers:
        - name: webhook-server
          image: drlatt/webhook-server:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
