---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-reject-snakeoil-team
  labels:
    team: snakeoil
spec:
  containers:
    - name: nginx
      image: nginx:1.17.4
      ports:
        - containerPort: 80
